# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101yeneRQtYGIdikYG1GP3OSnT4qLfyWq
"""

import streamlit as st
import gtts
from gtts import gTTS
import os

# Tentukan direktori untuk menyimpan file audio sementara
TEMP_AUDIO_DIR = "temp_audio"
if not os.path.exists(TEMP_AUDIO_DIR):
    os.makedirs(TEMP_AUDIO_DIR)

# --- FUNGSI-FUNGSI UTAMA ---

def text_to_speech(text):
    """Mengubah teks menjadi file audio MP3."""
    tts = gTTS(text=text, lang='en')
    with open(f"{TEMP_AUDIO_DIR}/temp.mp3", "wb") as f:
        tts.write_to_fp(f)
    return f"{TEMP_AUDIO_DIR}/temp.mp3"

# --- DATA KOSAKATA ---

vocab_data = {
    "Hewan": [
        {'kata': 'Cat', 'terjemahan': 'Kucing', 'pelafalan': '(ket)'},
        {'kata': 'Dog', 'terjemahan': 'Anjing', 'pelafalan': '(dog)'},
        {'kata': 'Bird', 'terjemahan': 'Burung', 'pelafalan': '(berd)'},
        {'kata': 'Fish', 'terjemahan': 'Ikan', 'pelafalan': '(fish)'},
        {'kata': 'Elephant', 'terjemahan': 'Gajah', 'pelafalan': '(elefen)'},
        {'kata': 'Lion', 'terjemahan': 'Singa', 'pelafalan': '(laion)'}
    ],
    "Buah-buahan": [
        {'kata': 'Apple', 'terjemahan': 'Apel', 'pelafalan': '(epel)'},
        {'kata': 'Banana', 'terjemahan': 'Pisang', 'pelafalan': '(bænana)'},
        {'kata': 'Orange', 'terjemahan': 'Jeruk', 'pelafalan': '(orej)'},
        {'kata': 'Grape', 'terjemahan': 'Anggur', 'pelafalan': '(grep)'},
        {'kata': 'Mango', 'terjemahan': 'Mangga', 'pelafalan': '(menggo)'}
    ],
    "Warna": [
        {'kata': 'Red', 'terjemahan': 'Merah', 'pelafalan': '(red)'},
        {'kata': 'Blue', 'terjemahan': 'Biru', 'pelafalan': '(blu)'},
        {'kata': 'Green', 'terjemahan': 'Hijau', 'pelafalan': '(grin)'},
        {'kata': 'Yellow', 'terjemahan': 'Kuning', 'pelafalan': '(yelo)'},
        {'kata': 'Black', 'terjemahan': 'Hitam', 'pelafalan': '(blek)'}
    ],
    "Angka": [
        {'kata': 'One', 'terjemahan': 'Satu', 'pelafalan': '(wan)'},
        {'kata': 'Two', 'terjemahan': 'Dua', 'pelafalan': '(tu)'},
        {'kata': 'Three', 'terjemahan': 'Tiga', 'pelafalan': '(tri)'},
        {'kata': 'Four', 'terjemahan': 'Empat', 'pelafalan': '(for)'},
        {'kata': 'Five', 'terjemahan': 'Lima', 'pelafalan': '(faiv)'}
    ],
    "Bagian Tubuh": [
        {'kata': 'Head', 'terjemahan': 'Kepala', 'pelafalan': '(hed)'},
        {'kata': 'Hand', 'terjemahan': 'Tangan', 'pelafalan': '(hend)'},
        {'kata': 'Foot', 'terjemahan': 'Kaki', 'pelafalan': '(fut)'},
        {'kata': 'Eye', 'terjemahan': 'Mata', 'pelafalan': '(ai)'},
        {'kata': 'Ear', 'terjemahan': 'Telinga', 'pelafalan': '(ir)'}
    ],
    "Transportasi": [
        {'kata': 'Car', 'terjemahan': 'Mobil', 'pelafalan': '(kar)'},
        {'kata': 'Bus', 'terjemahan': 'Bus', 'pelafalan': '(bas)'},
        {'kata': 'Train', 'terjemahan': 'Kereta', 'pelafalan': '(tren)'},
        {'kata': 'Bicycle', 'terjemahan': 'Sepeda', 'pelafalan': '(baisikel)'},
        {'kata': 'Airplane', 'terjemahan': 'Pesawat', 'pelafalan': '(erplen)'}
    ],
    "Pakaian": [
        {'kata': 'Shirt', 'terjemahan': 'Kemeja', 'pelafalan': '(syert)'},
        {'kata': 'Pants', 'terjemahan': 'Celana', 'pelafalan': '(pents)'},
        {'kata': 'Dress', 'terjemahan': 'Gaun', 'pelafalan': '(dres)'},
        {'kata': 'Shoes', 'terjemahan': 'Sepatu', 'pelafalan': '(syus)'},
        {'kata': 'Hat', 'terjemahan': 'Topi', 'pelafalan': '(het)'}
    ],
    "Makanan": [
        {'kata': 'Bread', 'terjemahan': 'Roti', 'pelafalan': '(bred)'},
        {'kata': 'Rice', 'terjemahan': 'Nasi', 'pelafalan': '(rais)'},
        {'kata': 'Soup', 'terjemahan': 'Sup', 'pelafalan': '(sup)'},
        {'kata': 'Salad', 'terjemahan': 'Salad', 'pelafalan': '(seled)'},
        {'kata': 'Egg', 'terjemahan': 'Telur', 'pelafalan': '(eg)'}
    ],
    "Minuman": [
        {'kata': 'Water', 'terjemahan': 'Air', 'pelafalan': '(woter)'},
        {'kata': 'Milk', 'terjemahan': 'Susu', 'pelafalan': '(miluk)'},
        {'kata': 'Tea', 'terjemahan': 'Teh', 'pelafalan': '(ti)'},
        {'kata': 'Coffee', 'terjemahan': 'Kopi', 'pelafalan': '(kofi)'},
        {'kata': 'Juice', 'terjemahan': 'Jus', 'pelafalan': '(jus)'}
    ],
    "Profesi": [
        {'kata': 'Teacher', 'terjemahan': 'Guru', 'pelafalan': '(ticer)'},
        {'kata': 'Doctor', 'terjemahan': 'Dokter', 'pelafalan': '(doktor)'},
        {'kata': 'Engineer', 'terjemahan': 'Insinyur', 'pelafalan': '(enjinir)'},
        {'kata': 'Artist', 'terjemahan': 'Seniman', 'pelafalan': '(artis)'},
        {'kata': 'Chef', 'terjemahan': 'Koki', 'pelafalan': '(syef)'}
    ],
    "Negara": [
        {'kata': 'Indonesia', 'terjemahan': 'Indonesia', 'pelafalan': '(indonesia)'},
        {'kata': 'Japan', 'terjemahan': 'Jepang', 'pelafalan': '(jepen)'},
        {'kata': 'China', 'terjemahan': 'Tiongkok', 'pelafalan': '(caina)'},
        {'kata': 'USA', 'terjemahan': 'Amerika', 'pelafalan': '(yu es ei)'},
        {'kata': 'Germany', 'terjemahan': 'Jerman', 'pelafalan': '(jermani)'}
    ],
    "Olahraga": [
        {'kata': 'Football', 'terjemahan': 'Sepak bola', 'pelafalan': '(futbol)'},
        {'kata': 'Basketball', 'terjemahan': 'Bola basket', 'pelafalan': '(basketbol)'},
        {'kata': 'Swimming', 'terjemahan': 'Renang', 'pelafalan': '(swiming)'},
        {'kata': 'Tennis', 'terjemahan': 'Tenis', 'pelafalan': '(tenis)'},
        {'kata': 'Cycling', 'terjemahan': 'Bersepeda', 'pelafalan': '(saikling)'}
    ],
    "Keluarga": [
        {'kata': 'Father', 'terjemahan': 'Ayah', 'pelafalan': '(fader)'},
        {'kata': 'Mother', 'terjemahan': 'Ibu', 'pelafalan': '(mader)'},
        {'kata': 'Brother', 'terjemahan': 'Kakak/Adik Laki-laki', 'pelafalan': '(brader)'},
        {'kata': 'Sister', 'terjemahan': 'Kakak/Adik Perempuan', 'pelafalan': '(sister)'},
        {'kata': 'Grandmother', 'terjemahan': 'Nenek', 'pelafalan': '(grendmader)'}
    ],
    "Musim": [
        {'kata': 'Summer', 'terjemahan': 'Musim panas', 'pelafalan': '(samer)'},
        {'kata': 'Winter', 'terjemahan': 'Musim dingin', 'pelafalan': '(winter)'},
        {'kata': 'Spring', 'terjemahan': 'Musim semi', 'pelafalan': '(spring)'},
        {'kata': 'Autumn', 'terjemahan': 'Musim gugur', 'pelafalan': '(otem)'}
    ],
    "Cuaca": [
        {'kata': 'Sunny', 'terjemahan': 'Cerah', 'pelafalan': '(sani)'},
        {'kata': 'Cloudy', 'terjemahan': 'Berawan', 'pelafalan': '(klaudi)'},
        {'kata': 'Rainy', 'terjemahan': 'Hujan', 'pelafalan': '(reni)'},
        {'kata': 'Windy', 'terjemahan': 'Berangin', 'pelafalan': '(windi)'}
    ],
    "Perasaan": [
        {'kata': 'Happy', 'terjemahan': 'Senang', 'pelafalan': '(hepi)'},
        {'kata': 'Sad', 'terjemahan': 'Sedih', 'pelafalan': '(sed)'},
        {'kata': 'Angry', 'terjemahan': 'Marah', 'pelafalan': '(enggri)'},
        {'kata': 'Scared', 'terjemahan': 'Takut', 'pelafalan': '(skerd)'}
    ]
}

# --- KONFIGURASI TEMA DAN KUSTOMISASI CSS ---

# Setel tema default ke mode terang
st.set_page_config(
    page_title="Kamus Kosakata Interaktif",
    page_icon="📚",
    layout="centered",
    initial_sidebar_state="expanded"
)

# Kustomisasi CSS untuk perpaduan biru dan putih
st.markdown("""
<style>
    /* Mengubah warna sidebar */
    .st-emotion-cache-121bd7t.e1ds3rsq1 {
        background-color: #f0f2f6;
        color: #0d47a1;
    }
    
    /* Warna teks di sidebar */
    .st-emotion-cache-vk3ypu.e1ds3rsq3 {
        color: #0d47a1;
    }
    
    /* Warna background utama */
    .st-emotion-cache-1cypj85.e1ds3rsq0 {
        background-color: #ffffff;
    }

    /* Kustomisasi button */
    .st-emotion-cache-6q9sum.e1ds3rsq1 {
        background-color: #0d47a1;
        color: white;
        border-radius: 8px;
        border: 1px solid #0d47a1;
    }
    .st-emotion-cache-6q9sum.e1ds3rsq1:hover {
        background-color: #1976d2;
    }
    .st-emotion-cache-14u43f8.e1ds3rsq1 {
        background-color: #1e88e5;
        color: white;
        border-radius: 8px;
        border: 1px solid #1e88e5;
    }
    .st-emotion-cache-14u43f8.e1ds3rsq1:hover {
        background-color: #2196f3;
    }
    
    /* Button untuk TTS & STT */
    .stButton > button {
        background-color: #1e88e5; /* Biru terang */
        color: white;
        border-radius: 5px;
        border: none;
        padding: 8px 12px;
        font-weight: bold;
    }
    .stButton > button:hover {
        background-color: #2196f3; /* Biru yang lebih terang saat hover */
    }

</style>
""", unsafe_allow_html=True)


# --- ANTARMUKA UTAMA STREAMLIT ---

def main():
    st.title("📚 Kamus Kosakata Inggris-Indonesia")
    st.markdown("""
    <p style="color:#666666;">
    Pilih topik di sidebar untuk melihat daftar kosakata. Klik tombol <span style="color:#1e88e5;">🔊</span> untuk mendengarkan pengucapan.
    </p>
    """, unsafe_allow_html=True)
    st.markdown("⚠️ **Catatan**: Fitur Speech-to-Text (🎙️) tidak dapat berfungsi di platform ini karena masalah kompatibilitas library.")

    st.write("---")

    # Sidebar untuk memilih topik dan tema
    st.sidebar.title("Pengaturan")
    
    # Fitur untuk mengubah tema
    theme_option = st.sidebar.radio(
        "Pilih Tema Latar Belakang",
        ("Terang (Biru & Putih)", "Gelap (Default)")
    )

    if theme_option == "Terang (Biru & Putih)":
        st.session_state['theme'] = 'light'
    else:
        st.session_state['theme'] = 'dark'
        
    st.sidebar.markdown("---")
    
    st.sidebar.title("Pilih Topik")
    topic_list = list(vocab_data.keys())
    selected_topic = st.sidebar.radio("Daftar Topik", topic_list)
    
    st.header(f"Topik: {selected_topic}")
    
    vocabularies = vocab_data.get(selected_topic, [])
    
    for i, vocab in enumerate(vocabularies):
        word = vocab['kata']
        translation = vocab['terjemahan']
        pronunciation = vocab['pelafalan']
        
        # Mengubah tata letak karena tidak ada tombol STT lagi
        col1, col2, col3 = st.columns([0.4, 0.4, 0.2])
        
        with col1:
            st.markdown(f"**{word}**")
        with col2:
            st.markdown(f"*{translation}* ({pronunciation})")
            
        with col3:
            # Tombol TTS untuk memutar audio
            if st.button("🔊", key=f"tts_{word}_{i}"):
                audio_file_path = text_to_speech(word)
                with open(audio_file_path, "rb") as f:
                    audio_bytes = f.read()
                    st.audio(audio_bytes, format='audio/mp3', start_time=0)
                # Hapus file audio setelah digunakan
                os.remove(audio_file_path)

if __name__ == "__main__":
    main()
